// generated by scripts/build-pages.sh
export const ODPT_TOKENS = { public: 'b0mg7xyln1e8yd2d2uh2z4hea92r4zjphrkqsvmuzjqos1cdxi1ovwgoeoul7g78', challenge: '4venni83t6gaq25zkzgkwbp12ttn290qwvydonhs5si6g8mrdvpykjwezplekez9' };
